### ISSUE TITLE
사파리에서 비디오가 출력되지 않는 현상

### ISSUE THREAD

**Issue by kimregular** [SeJonJ/ChatForYou#31]
플랫폼
공통(pc)

카테고리
사파리에서 화상 채팅 방 생성, 입장
비디오 녹화 허용

상세
해당 설정을 하였음에도 화면에 비디오가 출력되지 않습니다.

<img width="1440" alt="image" src="https://github.com/SeJonJ/Spring-WebSocket-WebRTC-Chatting/assets/82751941/b2b02067-3562-48f7-82c6-d0a074dd5b81">

**Comment by kimregular** [comment]
@SeJonJ  언제 해결하실 예정이죠?

**Comment by SeJonJ** [comment]
@kimregular 

ChatForYou 서비스는 사파리 환경에 대해 지원하고 있지 않습니다.
추후 지원예정에는 있으나 현재로서는 업데이트 대상이 아닙니다. 크롬 또는 크로미움 기반 브라우저 사용을 권장드립니다.

**Comment by kimregular** [comment]
엠병
